In [13]:
import numpy as np
import cv2
from scipy.signal import convolve2d

# Loading the image from the specified location
gr_im = cv2.imread(r"C:\Users\risha\Desktop\2nd term\Computer vision\assignment\CA_2024\CA_2024\data\shapes.png", cv2.IMREAD_GRAYSCALE)

# Defining the Sobel operators for horizontal and vertical gradients
kx = np.array([[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]], dtype=np.int32)
ky = np.array([[1, 2, 1], [0, 0, 0], [-1, -2, -1]], dtype=np.int32)

def compute_gradient_magnitude(gr_im, kx, ky):
    # Apply convolution with the horizontal and vertical kernels
    gx = convolve2d(gr_im, kx, mode='same', boundary='fill', fillvalue=0)
    gy = convolve2d(gr_im, ky, mode='same', boundary='fill', fillvalue=0)
    # Calculate the gradient magnitude
    grad_magnitude = np.sqrt(gx**2 + gy**2)
    return grad_magnitude.astype(np.float64)

def compute_gradient_direction(gr_im, kx, ky):
    # Apply convolution with the horizontal and vertical kernels
    gx = convolve2d(gr_im, kx, mode='same', boundary='fill', fillvalue=0)
    gy = convolve2d(gr_im, ky, mode='same', boundary='fill', fillvalue=0)
    # Calculate the gradient direction
    grad_direction = np.arctan2(gy, gx)
    return grad_direction.astype(np.float64)

# Computing the gradient magnitude and direction for the given image
grad_magnitude = compute_gradient_magnitude(gr_im, kx, ky)
grad_direction = compute_gradient_direction(gr_im, kx, ky)

# Returning the shapes of the resulting arrays to verify correctness
print(grad_magnitude.shape, grad_direction.shape,grad_direction.dtype)

# Computing the gradient magnitude and direction for the given image
grad_magnitude = compute_gradient_magnitude(gr_im, kx, ky)
grad_direction = compute_gradient_direction(gr_im, kx, ky)

# Printing the gradient magnitude and direction arrays
print("Gradient Magnitude:")
print(grad_magnitude)

print("\nGradient Direction:")
print(grad_direction)


(720, 720) (720, 720) float64
Gradient Magnitude:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

Gradient Direction:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
